### ISSUE TITLE
boost::posix_time doesn't have an extended iso string constructor

### ISSUE THREAD

**Issue by lpatire** [boostorg/date_time#116] opened 2019-11-05 13:59 UTC
There is an output method: 

`std::string to_iso_extended_string(ptime)`

but no compatible constructor from the extended ISO format.
This could be a easy and simple idea to guarantee consistency between outwards and inwards methods.

**Comment by JeffGarland** [comment] 2019-11-21 16:23
This function already exists in later versions of boost past 1.54.  I believe the issue is that the documentation was not updated to match.

// posix_time/time_parsers.hpp
  inline ptime from_iso_extended_string(const std::string& s) {
    return date_time::parse_delimited_time<ptime>(s, 'T');
  }

**Comment by JeffGarland** [comment] 2020-04-05 18:22
This will be fixed in the 1.73 docs

**Comment by JeffGarland** [comment] 2020-07-09 15:10
closing -- doc update shipped with 1.73

**Closed by JeffGarland** 2020-07-09 15:10 UTC
